---
# Users Database
# Generate new passwords using: authelia hash-password 'your-password'
# This will create a password hash you can use below

users:
  admin:
    displayname: "Admin User"
    # Password is: changeme
    password: "$argon2id$v=19$m=65536,t=3,p=4$UQm6G+0tQzd2BGq9LCpxAg$qqN5WQMwD+YzQHVk7+oVRX2RBN7NLEVwqLVOhWUphGg"
    email: admin@example.com
    groups:
      - admins