services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      - authelia_config:/config
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - redis  # If using Redis for sessions
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9091/api/state"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:  # Optional but recommended for session storage
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  authelia_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/1tb/authelia/config
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/1tb/redis

networks:
  backend:
    driver: bridge