server:
  address: 'tcp://0.0.0.0:9091'

log:
  level: info

authentication_backend:
  file:
    path: /config/users_database.yml
  password_reset:
    disable: true  # Disable password reset since we haven't configured email yet

identity_validation:
  reset_password:
    jwt_secret: placeholder_jwt  # Will be overridden by env

access_control:
  default_policy: two_factor
  rules:
    - domain: "*.${DOMAIN:-7gram.xyz}"  # Change this to your domain
      policy: two_factor

session:
  name: authelia_session
  secret: placeholder_session  # Will be overridden by env
  expiration: 3600  # 1 hour
  inactivity: 300   # 5 minutes
  remember_me: 2592000  # 30 days
  cookies:
    - domain: 7gram.xyz  # Updated to new multi-domain format (single entry)
      authelia_url: https://auth.7gram.xyz  # Optional, but recommended
      same_site: lax  # If customizing

storage:
  encryption_key: placeholder_encryption  # Will be overridden by env
  postgres:
    address: authelia-postgres:5432
    database: placeholder_database  # Will be overridden by env
    username: placeholder_username  # Will be overridden by env
    password: placeholder_password  # Will be overridden by env

notifier:
  filesystem:
    filename: /config/notification.txt

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

theme: dark