services:
  # =============================================================================
  # PHOTO MANAGEMENT
  # =============================================================================

  # photoprism - dedicated photo management app
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    environment:
      - PHOTOPRISM_ADMIN_PASSWORD=${PHOTOPRISM_ADMIN_PASSWORD:-pleasechange}
      - PHOTOPRISM_SITE_URL=http://localhost:2342/
      - PHOTOPRISM_DATABASE_DRIVER=postgres
      - PHOTOPRISM_DATABASE_SERVER=postgres:5432
      - PHOTOPRISM_DATABASE_NAME=photoprism
      - PHOTOPRISM_DATABASE_USER=${PHOTOPRISM_DB_USER:-photoprism}
      - PHOTOPRISM_DATABASE_PASSWORD=${PHOTOPRISM_DB_PASSWORD:-changeme}
      - PHOTOPRISM_UID=${PUID:-1000}
      - PHOTOPRISM_GID=${PGID:-1000}
      - TZ=${TZ:-America/Toronto}
    volumes:
      - photos_originals:/photoprism/originals  # Mount your photo directory here
      - photoprism_storage:/photoprism/storage
    ports:
      - "2342:2342"
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:2342/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  photos_originals:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/1tb/photos
  photoprism_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/1tb/photoprism/storage