
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  external_url: "https://home.7gram.xyz"
  internal_url: "http://localhost:8123"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/16  # Docker backend network (nginx, etc.)
    - 172.19.0.0/16  # Additional docker network
    - 172.20.0.0/16  # Additional docker network
    - 172.17.0.1     # Docker host bridge
    - 172.21.0.0/16  # Additional docker network (nginx is here)
    - 172.22.0.0/16  # Additional docker network
    - 127.0.0.1
    - 172.18.0.7     # nginx container (explicit)
    - 172.19.0.7
    - 172.20.0.2
  ip_ban_enabled: false
  login_attempts_threshold: 10

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml