services:
  # =============================================================================
  # CLOUD STORAGE
  # =============================================================================

  # nextcloud - file sharing with postgres db
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Toronto}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME:-nextcloud}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER:-nextcloud}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD:-changeme}
    volumes:
      - nextcloud_config:/config
      - nextcloud_data:/data
    ports:
      - "8443:443"
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/status.php", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  nextcloud_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/1tb/nextcloud/config
  nextcloud_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/1tb/nextcloud/data