services:
  # =============================================================================
  # DATABASE SERVICES
  # =============================================================================

  # postgres - database for nextcloud and photoprism
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME:-nextcloud}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - NEXTCLOUD_DB_USER=${NEXTCLOUD_DB_USER:-nextcloud}
      - NEXTCLOUD_DB_PASSWORD=${NEXTCLOUD_DB_PASSWORD:-changeme}
      - PHOTOPRISM_DB_USER=${PHOTOPRISM_DB_USER:-photoprism}
      - PHOTOPRISM_DB_PASSWORD=${PHOTOPRISM_DB_PASSWORD:-changeme}
      - TZ=${TZ:-America/Toronto}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/1tb/postgres