name: Deploy Freddy via Shared Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      action_type:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - deploy
          - restart
          - destroy
          - health-check
        default: deploy

jobs:
  deploy:
    name: Deploy Freddy (home)
    uses: nuniesmith/actions/.github/workflows/deploy.yml@main
    with:
      service_name: 'freddy'
      action_type: ${{ inputs.action_type || 'deploy' }}
      deployment_mode: 'home'
      home_target_host: 'freddy'
      home_service_user: 'freddy_user'
      home_repo_url: 'https://github.com/nuniesmith/freddy.git'
      jump_host: 'nginx.7gram.xyz'
      domain_suffix: '7gram.xyz'
    secrets:
      LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
      SERVICE_ROOT_PASSWORD: ${{ secrets.SERVICE_ROOT_PASSWORD }}
      ACTIONS_USER_PASSWORD: ${{ secrets.ACTIONS_USER_PASSWORD }}
      JORDAN_PASSWORD: ${{ secrets.JORDAN_PASSWORD }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      TAILSCALE_TAILNET: ${{ secrets.TAILSCALE_TAILNET }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      SERVICE_USER_PASSWORD: ${{ secrets.SERVICE_USER_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      HOME_ROOT_SSH_KEY: ${{ secrets.HOME_ROOT_SSH_KEY }}
